<?xml version="1.0"?>
<package>
  <name>xfeatvins</name>
  <version>0.0.0</version>
  <description>The xfeatvins package</description>
  <maintainer email="luohongkun0715@gmail.com">Luo Hongkun</maintainer>

  <license>GPLv3</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>image_transport</build_depend>
  <build_depend>camera_models</build_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>message_filters</build_depend>
  <build_depend>nodelet</build_depend>
  <build_depend>vins_nodelet_pkg</build_depend>
  <run_depend>message_runtime</run_depend>
  <run_depend>roscpp</run_depend>
  <run_depend>image_transport</run_depend>
  <run_depend>camera_models</run_depend>
  <run_depend>nodelet</run_depend>
  <run_depend>message_filters</run_depend>
  <run_depend>vins_nodelet_pkg</run_depend>

  <export>
  </export>
</package>
