%YAML:1.0
---
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "/sensor_bridge/imu_raw"
image0_topic: "/hik_camera_1/sync_image"
image1_topic: "/hik_camera_2/sync_image"
# imu_topic: "/camera/imu"
# image0_topic: "/camera/infra1/image_rect_raw"
# image1_topic: "/camera/infra2/image_rect_raw"

cam0_calib: "cam0_mei.yaml"
cam1_calib: "cam1_mei.yaml"
image_width: 720
image_height: 540

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.


# Realsense D435i
# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [1, 0, 0, 0.00552000012248755,
#            0, 1, 0,  -0.00510000018402934,
#            0, 0, 1, -0.011739999987185,
#            0, 0, 0, 1]

# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [1, 0, 0, -0.0444315113127232,
#            0, 1, 0,  -0.00510000018402934,
#            0, 0, 1, -0.011739999987185,
#            0, 0, 0, 1]

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0, -1, 0, 0.055,
           -1, 0, 0,  0,
           0, 0, -1, -0.01,
           0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0, -1, 0, -0.055,
           -1, 0, 0,  0,
           0, 0, -1, -0.01,
           0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#Gpu accleration support
use_gpu: 1
use_gpu_acc_flow: 0

#feature traker paprameters
# max feature number in feature tracking
max_cnt: 150

# min distance between two features 
min_dist: 10

#matcher parameters
matche_score_threshold: 0.7
ransacReprojThreshold: 0.5

freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

# Path to vio output results
output_path: "xfeatvins/xfeatvins_estimator/vio_output"

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "xfeatvins/xfeatvins_estimator/vio_output" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

#deep learning feature points weights
extractor_weight_path: "xfeatvins/xfeatvins_estimator/weights_dpl/xfeat.engine"
matcher_weight_path: "xfeatvins/xfeatvins_estimator/weights_dpl/superpoint_lightglue_fused_cpu.onnx" 

# Bag of Words path
voc_relative_path: "xfeatvins/xfeatvins_loop_fusion/src/ThirdParty/Voc/superpoint1.yml.gz"

image_height: 640
image_width: 480
max_keypoints: 150
threshold: 0.05
kenel_size: 5
softmaxtemp: 1.0